// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hotgfdbuljpubgwunnwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvdGdmZGJ1bGpwdWJnd3VubndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjUzNzQsImV4cCI6MjA2MTk0MTM3NH0.hms3KSW882H8J528_GEim-0OOBA7T8KGKzbn3QpPPb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);